apiVersion: v1
kind: ConfigMap
metadata:
  name: shop-backend
  namespace: {{ .Values.namespace }}
  labels:
    {{ include "shop.labels" . | nindent 4 }}
data:
  APP_NAME: {{ .Values.backend.env.APP_NAME | quote }}
  OTEL_SERVICE_NAME: {{ .Values.backend.env.OTEL_SERVICE_NAME | quote }}
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.backend.env.OTEL_EXPORTER_OTLP_ENDPOINT | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: shop-backend
  namespace: {{ .Values.namespace }}
  labels:
    {{ include "shop.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.backend.databaseUrl | default "" | quote }}
