{{- if .Values.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: shop-backend
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    {{- if eq .Values.strategy "rolling" }}
    apiVersion: apps/v1
    kind: Deployment
    {{- else }}
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    {{- end }}
    name: shop-backend
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.cpuAverageUtilization }}
{{- end }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: shop-backend
  namespace: {{ .Values.namespace }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      app: shop-backend
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: shop-frontend
  namespace: {{ .Values.namespace }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      app: shop-frontend
